org: sebastianchu
service: api-compras

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30
  iam:
    role: arn:aws:iam::971808350791:role/LabRole
  environment:
    TABLE_NAME: ComprasTable-dev
    JWT_SECRET: ${env:JWT_SECRET}

package:
  include:
    - node_modules/**
    - handler.js
    - utils.js/**

functions:
  comprar:
    handler: handler.comprar
    events:
      - http:
          path: /compras
          method: post
          cors: true

  obtenerCompras:
    handler: handler.obtenerCompras
    events:
      - http:
          path: /compras
          method: get
          cors: true

resources:
  Resources:
    ComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ComprasTable-dev
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

